version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
